version: '3.8'
services:
  api:
    build: .
    container_name: api
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - .docker/mongo:/data/db

volumes:
  mongo:
